version: '3.8'
services:
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/test_data/students.sql:/docker-entrypoint-initdb.d/02_students.sql
      - ./db/test_data/lectures.sql:/docker-entrypoint-initdb.d/04_lectures.sql
      - ./db/test_data/instructors.sql:/docker-entrypoint-initdb.d/03_instructors.sql
      - ./db/test_data/enrollments.sql:/docker-entrypoint-initdb.d/05_enrollments.sql
      - ./db/test_data/lecture_student_counts.sql:/docker-entrypoint-initdb.d/06_lecture_student_counts.sql
  app:
    image: node:16
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install -g nodemon && npm install && nodemon --exec ts-node src/main/index.ts"
    depends_on:
      - db
    ports:
      - "3000:3000"
